//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Sofii.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISofiiListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SofiiBaseListener : ISofiiListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] SofiiParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] SofiiParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.within_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithin_stmt([NotNull] SofiiParser.Within_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.within_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithin_stmt([NotNull] SofiiParser.Within_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.use_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUse_stmt([NotNull] SofiiParser.Use_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.use_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUse_stmt([NotNull] SofiiParser.Use_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SofiiParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SofiiParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.enum_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_def([NotNull] SofiiParser.Enum_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.enum_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_def([NotNull] SofiiParser.Enum_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.generic_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_params([NotNull] SofiiParser.Generic_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.generic_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_params([NotNull] SofiiParser.Generic_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.enum_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_case([NotNull] SofiiParser.Enum_caseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.enum_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_case([NotNull] SofiiParser.Enum_caseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.trait_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrait_def([NotNull] SofiiParser.Trait_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.trait_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrait_def([NotNull] SofiiParser.Trait_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.trait_method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrait_method([NotNull] SofiiParser.Trait_methodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.trait_method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrait_method([NotNull] SofiiParser.Trait_methodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.class_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_def([NotNull] SofiiParser.Class_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.class_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_def([NotNull] SofiiParser.Class_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_body([NotNull] SofiiParser.Class_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_body([NotNull] SofiiParser.Class_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_def([NotNull] SofiiParser.Const_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_def([NotNull] SofiiParser.Const_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.var_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_def([NotNull] SofiiParser.Var_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.var_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_def([NotNull] SofiiParser.Var_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.macro_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_def([NotNull] SofiiParser.Macro_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.macro_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_def([NotNull] SofiiParser.Macro_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.func_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_def([NotNull] SofiiParser.Func_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.func_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_def([NotNull] SofiiParser.Func_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.init_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit_def([NotNull] SofiiParser.Init_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.init_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit_def([NotNull] SofiiParser.Init_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.param_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_list([NotNull] SofiiParser.Param_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.param_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_list([NotNull] SofiiParser.Param_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] SofiiParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] SofiiParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] SofiiParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] SofiiParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.generic_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_type([NotNull] SofiiParser.Generic_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.generic_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_type([NotNull] SofiiParser.Generic_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_stmt([NotNull] SofiiParser.Assign_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_stmt([NotNull] SofiiParser.Assign_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_stmt([NotNull] SofiiParser.Return_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_stmt([NotNull] SofiiParser.Return_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] SofiiParser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] SofiiParser.If_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_stmt([NotNull] SofiiParser.For_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_stmt([NotNull] SofiiParser.For_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_stmt([NotNull] SofiiParser.While_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_stmt([NotNull] SofiiParser.While_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_stmt([NotNull] SofiiParser.Switch_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_stmt([NotNull] SofiiParser.Switch_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.switch_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_case([NotNull] SofiiParser.Switch_caseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.switch_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_case([NotNull] SofiiParser.Switch_caseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.guard_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard_stmt([NotNull] SofiiParser.Guard_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.guard_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard_stmt([NotNull] SofiiParser.Guard_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambda_expression([NotNull] SofiiParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.lambda_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambda_expression([NotNull] SofiiParser.Lambda_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] SofiiParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] SofiiParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.expression_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_stmt([NotNull] SofiiParser.Expression_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.expression_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_stmt([NotNull] SofiiParser.Expression_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SofiiParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SofiiParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] SofiiParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] SofiiParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.command_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand_call([NotNull] SofiiParser.Command_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.command_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand_call([NotNull] SofiiParser.Command_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call([NotNull] SofiiParser.Func_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call([NotNull] SofiiParser.Func_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.macro_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_call([NotNull] SofiiParser.Macro_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.macro_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_call([NotNull] SofiiParser.Macro_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.object_creation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_creation([NotNull] SofiiParser.Object_creationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.object_creation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_creation([NotNull] SofiiParser.Object_creationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access([NotNull] SofiiParser.Member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access([NotNull] SofiiParser.Member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SofiiParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] SofiiParser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SofiiParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] SofiiParser.OperatorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
