//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Sofii.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class SofiiParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WITHIN=1, USE=2, FUNC=3, CLASS=4, CONST=5, VAR=6, MACRO=7, TRAITS=8, IF=9, 
		ELSE=10, FOR=11, WHILE=12, SWITCH=13, CASE=14, ENUM=15, RETURN=16, GUARD=17, 
		PLUS=18, MINUS=19, STAR=20, SLASH=21, ASSIGN=22, EQUAL=23, NOTEQUAL=24, 
		LT=25, GT=26, LTE=27, GTE=28, AND=29, OR=30, NOT=31, LPAREN=32, RPAREN=33, 
		LBRACE=34, RBRACE=35, LBRACKET=36, RBRACKET=37, SEMICOLON=38, COLON=39, 
		COMMA=40, DOT=41, ARROW=42, IN=43, IDENTIFIER=44, INT_LITERAL=45, FLOAT_LITERAL=46, 
		STRING_LITERAL=47, BOOL_LITERAL=48, LINE_COMMENT=49, BLOCK_COMMENT=50, 
		WS=51;
	public const int
		RULE_program = 0, RULE_within_stmt = 1, RULE_use_stmt = 2, RULE_statement = 3, 
		RULE_enum_def = 4, RULE_generic_params = 5, RULE_enum_case = 6, RULE_traits_def = 7, 
		RULE_class_def = 8, RULE_const_def = 9, RULE_macro_def = 10, RULE_func_def = 11, 
		RULE_param_list = 12, RULE_param = 13, RULE_type = 14, RULE_generic_type = 15, 
		RULE_var_def = 16, RULE_assign_stmt = 17, RULE_return_stmt = 18, RULE_if_stmt = 19, 
		RULE_for_stmt = 20, RULE_while_stmt = 21, RULE_switch_stmt = 22, RULE_switch_case = 23, 
		RULE_block = 24, RULE_expression_stmt = 25, RULE_expression = 26, RULE_primary = 27, 
		RULE_func_call = 28, RULE_member_access = 29, RULE_operator = 30;
	public static readonly string[] ruleNames = {
		"program", "within_stmt", "use_stmt", "statement", "enum_def", "generic_params", 
		"enum_case", "traits_def", "class_def", "const_def", "macro_def", "func_def", 
		"param_list", "param", "type", "generic_type", "var_def", "assign_stmt", 
		"return_stmt", "if_stmt", "for_stmt", "while_stmt", "switch_stmt", "switch_case", 
		"block", "expression_stmt", "expression", "primary", "func_call", "member_access", 
		"operator"
	};

	private static readonly string[] _LiteralNames = {
		null, "'within'", "'use'", "'func'", "'class'", "'const'", "'var'", "'macro'", 
		"'traits'", "'if'", "'else'", "'for'", "'while'", "'switch'", "'case'", 
		"'enum'", "'return'", "'guard'", "'+'", "'-'", "'*'", "'/'", "'='", "'=='", 
		"'!='", "'<'", "'>'", "'<='", "'>='", "'&&'", "'||'", "'!'", "'('", "')'", 
		"'{'", "'}'", "'['", "']'", "';'", "':'", "','", "'.'", "'->'", "'in'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WITHIN", "USE", "FUNC", "CLASS", "CONST", "VAR", "MACRO", "TRAITS", 
		"IF", "ELSE", "FOR", "WHILE", "SWITCH", "CASE", "ENUM", "RETURN", "GUARD", 
		"PLUS", "MINUS", "STAR", "SLASH", "ASSIGN", "EQUAL", "NOTEQUAL", "LT", 
		"GT", "LTE", "GTE", "AND", "OR", "NOT", "LPAREN", "RPAREN", "LBRACE", 
		"RBRACE", "LBRACKET", "RBRACKET", "SEMICOLON", "COLON", "COMMA", "DOT", 
		"ARROW", "IN", "IDENTIFIER", "INT_LITERAL", "FLOAT_LITERAL", "STRING_LITERAL", 
		"BOOL_LITERAL", "LINE_COMMENT", "BLOCK_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sofii.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SofiiParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SofiiParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SofiiParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Use_stmtContext[] use_stmt() {
			return GetRuleContexts<Use_stmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Use_stmtContext use_stmt(int i) {
			return GetRuleContext<Use_stmtContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Within_stmtContext[] within_stmt() {
			return GetRuleContexts<Within_stmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Within_stmtContext within_stmt(int i) {
			return GetRuleContext<Within_stmtContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767490526L) != 0)) {
				{
				State = 65;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case USE:
					{
					State = 62;
					use_stmt();
					}
					break;
				case WITHIN:
					{
					State = 63;
					within_stmt();
					}
					break;
				case FUNC:
				case CLASS:
				case VAR:
				case MACRO:
				case TRAITS:
				case IF:
				case FOR:
				case WHILE:
				case SWITCH:
				case ENUM:
				case RETURN:
				case IDENTIFIER:
				case INT_LITERAL:
				case FLOAT_LITERAL:
				case STRING_LITERAL:
				case BOOL_LITERAL:
					{
					State = 64;
					statement();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 69;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Within_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITHIN() { return GetToken(SofiiParser.WITHIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Within_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_within_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterWithin_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitWithin_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Within_stmtContext within_stmt() {
		Within_stmtContext _localctx = new Within_stmtContext(Context, State);
		EnterRule(_localctx, 2, RULE_within_stmt);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(WITHIN);
			State = 71;
			Match(IDENTIFIER);
			State = 75;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 72;
					statement();
					}
					} 
				}
				State = 77;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Use_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USE() { return GetToken(SofiiParser.USE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(SofiiParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(SofiiParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(SofiiParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(SofiiParser.DOT, i);
		}
		public Use_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_use_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterUse_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitUse_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Use_stmtContext use_stmt() {
		Use_stmtContext _localctx = new Use_stmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_use_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(USE);
			State = 79;
			Match(IDENTIFIER);
			State = 84;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 80;
				Match(DOT);
				State = 81;
				Match(IDENTIFIER);
				}
				}
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Enum_defContext enum_def() {
			return GetRuleContext<Enum_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Traits_defContext traits_def() {
			return GetRuleContext<Traits_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_defContext class_def() {
			return GetRuleContext<Class_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext func_def() {
			return GetRuleContext<Func_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Macro_defContext macro_def() {
			return GetRuleContext<Macro_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_defContext var_def() {
			return GetRuleContext<Var_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Assign_stmtContext assign_stmt() {
			return GetRuleContext<Assign_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Return_stmtContext return_stmt() {
			return GetRuleContext<Return_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public If_stmtContext if_stmt() {
			return GetRuleContext<If_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_stmtContext for_stmt() {
			return GetRuleContext<For_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public While_stmtContext while_stmt() {
			return GetRuleContext<While_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Switch_stmtContext switch_stmt() {
			return GetRuleContext<Switch_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_stmtContext expression_stmt() {
			return GetRuleContext<Expression_stmtContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement);
		try {
			State = 100;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 87;
				enum_def();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 88;
				traits_def();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 89;
				class_def();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 90;
				func_def();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 91;
				macro_def();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 92;
				var_def();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 93;
				assign_stmt();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 94;
				return_stmt();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 95;
				if_stmt();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 96;
				for_stmt();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 97;
				while_stmt();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 98;
				switch_stmt();
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 99;
				expression_stmt();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENUM() { return GetToken(SofiiParser.ENUM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Generic_paramsContext generic_params() {
			return GetRuleContext<Generic_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_caseContext[] enum_case() {
			return GetRuleContexts<Enum_caseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_caseContext enum_case(int i) {
			return GetRuleContext<Enum_caseContext>(i);
		}
		public Enum_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterEnum_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitEnum_def(this);
		}
	}

	[RuleVersion(0)]
	public Enum_defContext enum_def() {
		Enum_defContext _localctx = new Enum_defContext(Context, State);
		EnterRule(_localctx, 8, RULE_enum_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			Match(ENUM);
			State = 103;
			Match(IDENTIFIER);
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LT) {
				{
				State = 104;
				generic_params();
				}
			}

			State = 107;
			Match(LBRACE);
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CASE) {
				{
				{
				State = 108;
				enum_case();
				}
				}
				State = 113;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 114;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Generic_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(SofiiParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(SofiiParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(SofiiParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(SofiiParser.COMMA, i);
		}
		public Generic_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_generic_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterGeneric_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitGeneric_params(this);
		}
	}

	[RuleVersion(0)]
	public Generic_paramsContext generic_params() {
		Generic_paramsContext _localctx = new Generic_paramsContext(Context, State);
		EnterRule(_localctx, 10, RULE_generic_params);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			Match(LT);
			State = 117;
			type();
			State = 122;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 118;
				Match(COMMA);
				State = 119;
				type();
				}
				}
				State = 124;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 125;
			Match(GT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_caseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CASE() { return GetToken(SofiiParser.CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(SofiiParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(SofiiParser.RPAREN, 0); }
		public Enum_caseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_case; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterEnum_case(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitEnum_case(this);
		}
	}

	[RuleVersion(0)]
	public Enum_caseContext enum_case() {
		Enum_caseContext _localctx = new Enum_caseContext(Context, State);
		EnterRule(_localctx, 12, RULE_enum_case);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			Match(CASE);
			State = 128;
			Match(IDENTIFIER);
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LPAREN) {
				{
				State = 129;
				Match(LPAREN);
				State = 130;
				type();
				State = 131;
				Match(RPAREN);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Traits_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRAITS() { return GetToken(SofiiParser.TRAITS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext[] func_def() {
			return GetRuleContexts<Func_defContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext func_def(int i) {
			return GetRuleContext<Func_defContext>(i);
		}
		public Traits_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_traits_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterTraits_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitTraits_def(this);
		}
	}

	[RuleVersion(0)]
	public Traits_defContext traits_def() {
		Traits_defContext _localctx = new Traits_defContext(Context, State);
		EnterRule(_localctx, 14, RULE_traits_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			Match(TRAITS);
			State = 136;
			Match(IDENTIFIER);
			State = 137;
			Match(LBRACE);
			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==FUNC) {
				{
				{
				State = 138;
				func_def();
				}
				}
				State = 143;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 144;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(SofiiParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(SofiiParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(SofiiParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(SofiiParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Const_defContext[] const_def() {
			return GetRuleContexts<Const_defContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Const_defContext const_def(int i) {
			return GetRuleContext<Const_defContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext[] func_def() {
			return GetRuleContexts<Func_defContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext func_def(int i) {
			return GetRuleContext<Func_defContext>(i);
		}
		public Class_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterClass_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitClass_def(this);
		}
	}

	[RuleVersion(0)]
	public Class_defContext class_def() {
		Class_defContext _localctx = new Class_defContext(Context, State);
		EnterRule(_localctx, 16, RULE_class_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(CLASS);
			State = 147;
			Match(IDENTIFIER);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 148;
				Match(COLON);
				State = 149;
				Match(IDENTIFIER);
				}
			}

			State = 152;
			Match(LBRACE);
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==FUNC || _la==CONST) {
				{
				State = 155;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case CONST:
					{
					State = 153;
					const_def();
					}
					break;
				case FUNC:
					{
					State = 154;
					func_def();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 160;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Const_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONST() { return GetToken(SofiiParser.CONST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(SofiiParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(SofiiParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(SofiiParser.SEMICOLON, 0); }
		public Const_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_const_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterConst_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitConst_def(this);
		}
	}

	[RuleVersion(0)]
	public Const_defContext const_def() {
		Const_defContext _localctx = new Const_defContext(Context, State);
		EnterRule(_localctx, 18, RULE_const_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162;
			Match(CONST);
			State = 163;
			Match(IDENTIFIER);
			State = 164;
			Match(COLON);
			State = 165;
			type();
			State = 166;
			Match(ASSIGN);
			State = 167;
			expression();
			State = 168;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Macro_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MACRO() { return GetToken(SofiiParser.MACRO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(SofiiParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(SofiiParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(SofiiParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(SofiiParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Macro_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_macro_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterMacro_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitMacro_def(this);
		}
	}

	[RuleVersion(0)]
	public Macro_defContext macro_def() {
		Macro_defContext _localctx = new Macro_defContext(Context, State);
		EnterRule(_localctx, 20, RULE_macro_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			Match(MACRO);
			State = 171;
			Match(IDENTIFIER);
			State = 172;
			Match(LT);
			State = 173;
			Match(IDENTIFIER);
			State = 174;
			Match(GT);
			State = 175;
			Match(LBRACE);
			State = 179;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767490520L) != 0)) {
				{
				{
				State = 176;
				statement();
				}
				}
				State = 181;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 182;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNC() { return GetToken(SofiiParser.FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(SofiiParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(SofiiParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Param_listContext param_list() {
			return GetRuleContext<Param_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(SofiiParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Func_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterFunc_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitFunc_def(this);
		}
	}

	[RuleVersion(0)]
	public Func_defContext func_def() {
		Func_defContext _localctx = new Func_defContext(Context, State);
		EnterRule(_localctx, 22, RULE_func_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(FUNC);
			State = 185;
			Match(IDENTIFIER);
			State = 186;
			Match(LPAREN);
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENTIFIER) {
				{
				State = 187;
				param_list();
				}
			}

			State = 190;
			Match(RPAREN);
			State = 193;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ARROW) {
				{
				State = 191;
				Match(ARROW);
				State = 192;
				type();
				}
			}

			State = 195;
			Match(LBRACE);
			State = 199;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767490520L) != 0)) {
				{
				{
				State = 196;
				statement();
				}
				}
				State = 201;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 202;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParamContext[] param() {
			return GetRuleContexts<ParamContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParamContext param(int i) {
			return GetRuleContext<ParamContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(SofiiParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(SofiiParser.COMMA, i);
		}
		public Param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterParam_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitParam_list(this);
		}
	}

	[RuleVersion(0)]
	public Param_listContext param_list() {
		Param_listContext _localctx = new Param_listContext(Context, State);
		EnterRule(_localctx, 24, RULE_param_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			param();
			State = 209;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 205;
				Match(COMMA);
				State = 206;
				param();
				}
				}
				State = 211;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(SofiiParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterParam(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitParam(this);
		}
	}

	[RuleVersion(0)]
	public ParamContext param() {
		ParamContext _localctx = new ParamContext(Context, State);
		EnterRule(_localctx, 26, RULE_param);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 212;
			Match(IDENTIFIER);
			State = 213;
			Match(COLON);
			State = 214;
			type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Generic_typeContext generic_type() {
			return GetRuleContext<Generic_typeContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 28, RULE_type);
		try {
			State = 218;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 216;
				Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 217;
				generic_type();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Generic_typeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(SofiiParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(SofiiParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(SofiiParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(SofiiParser.COMMA, i);
		}
		public Generic_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_generic_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterGeneric_type(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitGeneric_type(this);
		}
	}

	[RuleVersion(0)]
	public Generic_typeContext generic_type() {
		Generic_typeContext _localctx = new Generic_typeContext(Context, State);
		EnterRule(_localctx, 30, RULE_generic_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 220;
			Match(IDENTIFIER);
			State = 221;
			Match(LT);
			State = 222;
			type();
			State = 227;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 223;
				Match(COMMA);
				State = 224;
				type();
				}
				}
				State = 229;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 230;
			Match(GT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VAR() { return GetToken(SofiiParser.VAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(SofiiParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(SofiiParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(SofiiParser.SEMICOLON, 0); }
		public Var_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterVar_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitVar_def(this);
		}
	}

	[RuleVersion(0)]
	public Var_defContext var_def() {
		Var_defContext _localctx = new Var_defContext(Context, State);
		EnterRule(_localctx, 32, RULE_var_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232;
			Match(VAR);
			State = 233;
			Match(IDENTIFIER);
			State = 234;
			Match(COLON);
			State = 235;
			type();
			State = 236;
			Match(ASSIGN);
			State = 237;
			expression();
			State = 238;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assign_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(SofiiParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(SofiiParser.SEMICOLON, 0); }
		public Assign_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assign_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterAssign_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitAssign_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Assign_stmtContext assign_stmt() {
		Assign_stmtContext _localctx = new Assign_stmtContext(Context, State);
		EnterRule(_localctx, 34, RULE_assign_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 240;
			Match(IDENTIFIER);
			State = 241;
			Match(ASSIGN);
			State = 242;
			expression();
			State = 243;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(SofiiParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(SofiiParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Return_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterReturn_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitReturn_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Return_stmtContext return_stmt() {
		Return_stmtContext _localctx = new Return_stmtContext(Context, State);
		EnterRule(_localctx, 36, RULE_return_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			Match(RETURN);
			State = 247;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767376896L) != 0)) {
				{
				State = 246;
				expression();
				}
			}

			State = 249;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(SofiiParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(SofiiParser.ELSE, 0); }
		public If_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterIf_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitIf_stmt(this);
		}
	}

	[RuleVersion(0)]
	public If_stmtContext if_stmt() {
		If_stmtContext _localctx = new If_stmtContext(Context, State);
		EnterRule(_localctx, 38, RULE_if_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251;
			Match(IF);
			State = 252;
			expression();
			State = 253;
			block();
			State = 256;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 254;
				Match(ELSE);
				State = 255;
				block();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(SofiiParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(SofiiParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public For_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterFor_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitFor_stmt(this);
		}
	}

	[RuleVersion(0)]
	public For_stmtContext for_stmt() {
		For_stmtContext _localctx = new For_stmtContext(Context, State);
		EnterRule(_localctx, 40, RULE_for_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 258;
			Match(FOR);
			State = 259;
			Match(IDENTIFIER);
			State = 260;
			Match(IN);
			State = 261;
			expression();
			State = 262;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(SofiiParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public While_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterWhile_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitWhile_stmt(this);
		}
	}

	[RuleVersion(0)]
	public While_stmtContext while_stmt() {
		While_stmtContext _localctx = new While_stmtContext(Context, State);
		EnterRule(_localctx, 42, RULE_while_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264;
			Match(WHILE);
			State = 265;
			expression();
			State = 266;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Switch_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SWITCH() { return GetToken(SofiiParser.SWITCH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Switch_caseContext[] switch_case() {
			return GetRuleContexts<Switch_caseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Switch_caseContext switch_case(int i) {
			return GetRuleContext<Switch_caseContext>(i);
		}
		public Switch_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterSwitch_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitSwitch_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Switch_stmtContext switch_stmt() {
		Switch_stmtContext _localctx = new Switch_stmtContext(Context, State);
		EnterRule(_localctx, 44, RULE_switch_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			Match(SWITCH);
			State = 269;
			expression();
			State = 270;
			Match(LBRACE);
			State = 274;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CASE) {
				{
				{
				State = 271;
				switch_case();
				}
				}
				State = 276;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 277;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Switch_caseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CASE() { return GetToken(SofiiParser.CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(SofiiParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public Switch_caseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch_case; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterSwitch_case(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitSwitch_case(this);
		}
	}

	[RuleVersion(0)]
	public Switch_caseContext switch_case() {
		Switch_caseContext _localctx = new Switch_caseContext(Context, State);
		EnterRule(_localctx, 46, RULE_switch_case);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			Match(CASE);
			State = 280;
			expression();
			State = 281;
			Match(COLON);
			State = 282;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SofiiParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SofiiParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 48, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284;
			Match(LBRACE);
			State = 288;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767490520L) != 0)) {
				{
				{
				State = 285;
				statement();
				}
				}
				State = 290;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 291;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Expression_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterExpression_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitExpression_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Expression_stmtContext expression_stmt() {
		Expression_stmtContext _localctx = new Expression_stmtContext(Context, State);
		EnterRule(_localctx, 50, RULE_expression_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 293;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryContext[] primary() {
			return GetRuleContexts<PrimaryContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryContext primary(int i) {
			return GetRuleContext<PrimaryContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperatorContext[] @operator() {
			return GetRuleContexts<OperatorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperatorContext @operator(int i) {
			return GetRuleContext<OperatorContext>(i);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 52, RULE_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295;
			primary();
			State = 301;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4290510848L) != 0)) {
				{
				{
				State = 296;
				@operator();
				State = 297;
				primary();
				}
				}
				State = 303;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_LITERAL() { return GetToken(SofiiParser.INT_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_LITERAL() { return GetToken(SofiiParser.FLOAT_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(SofiiParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL_LITERAL() { return GetToken(SofiiParser.BOOL_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_accessContext member_access() {
			return GetRuleContext<Member_accessContext>(0);
		}
		public PrimaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primary; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterPrimary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitPrimary(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryContext primary() {
		PrimaryContext _localctx = new PrimaryContext(Context, State);
		EnterRule(_localctx, 54, RULE_primary);
		try {
			State = 311;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 304;
				Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 305;
				Match(INT_LITERAL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 306;
				Match(FLOAT_LITERAL);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 307;
				Match(STRING_LITERAL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 308;
				Match(BOOL_LITERAL);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 309;
				func_call();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 310;
				member_access();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(SofiiParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(SofiiParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(SofiiParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(SofiiParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(SofiiParser.COMMA, i);
		}
		public Func_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitFunc_call(this);
		}
	}

	[RuleVersion(0)]
	public Func_callContext func_call() {
		Func_callContext _localctx = new Func_callContext(Context, State);
		EnterRule(_localctx, 56, RULE_func_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 313;
			Match(IDENTIFIER);
			State = 314;
			Match(LPAREN);
			State = 323;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 545357767376896L) != 0)) {
				{
				State = 315;
				expression();
				State = 320;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 316;
					Match(COMMA);
					State = 317;
					expression();
					}
					}
					State = 322;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 325;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_accessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(SofiiParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(SofiiParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(SofiiParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(SofiiParser.DOT, i);
		}
		public Member_accessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_access; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterMember_access(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitMember_access(this);
		}
	}

	[RuleVersion(0)]
	public Member_accessContext member_access() {
		Member_accessContext _localctx = new Member_accessContext(Context, State);
		EnterRule(_localctx, 58, RULE_member_access);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 327;
			Match(IDENTIFIER);
			State = 330;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 328;
				Match(DOT);
				State = 329;
				Match(IDENTIFIER);
				}
				}
				State = 332;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==DOT );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(SofiiParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(SofiiParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STAR() { return GetToken(SofiiParser.STAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(SofiiParser.SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(SofiiParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUAL() { return GetToken(SofiiParser.NOTEQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(SofiiParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(SofiiParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LTE() { return GetToken(SofiiParser.LTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GTE() { return GetToken(SofiiParser.GTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(SofiiParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(SofiiParser.OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(SofiiParser.NOT, 0); }
		public OperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISofiiListener typedListener = listener as ISofiiListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
	}

	[RuleVersion(0)]
	public OperatorContext @operator() {
		OperatorContext _localctx = new OperatorContext(Context, State);
		EnterRule(_localctx, 60, RULE_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 334;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 4290510848L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,51,337,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,1,0,1,0,1,0,5,0,66,8,0,10,0,12,0,69,9,0,1,1,1,1,1,
		1,5,1,74,8,1,10,1,12,1,77,9,1,1,2,1,2,1,2,1,2,5,2,83,8,2,10,2,12,2,86,
		9,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,3,3,101,8,3,1,
		4,1,4,1,4,3,4,106,8,4,1,4,1,4,5,4,110,8,4,10,4,12,4,113,9,4,1,4,1,4,1,
		5,1,5,1,5,1,5,5,5,121,8,5,10,5,12,5,124,9,5,1,5,1,5,1,6,1,6,1,6,1,6,1,
		6,1,6,3,6,134,8,6,1,7,1,7,1,7,1,7,5,7,140,8,7,10,7,12,7,143,9,7,1,7,1,
		7,1,8,1,8,1,8,1,8,3,8,151,8,8,1,8,1,8,1,8,5,8,156,8,8,10,8,12,8,159,9,
		8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,5,10,178,8,10,10,10,12,10,181,9,10,1,10,1,10,1,11,1,11,1,11,1,11,
		3,11,189,8,11,1,11,1,11,1,11,3,11,194,8,11,1,11,1,11,5,11,198,8,11,10,
		11,12,11,201,9,11,1,11,1,11,1,12,1,12,1,12,5,12,208,8,12,10,12,12,12,211,
		9,12,1,13,1,13,1,13,1,13,1,14,1,14,3,14,219,8,14,1,15,1,15,1,15,1,15,1,
		15,5,15,226,8,15,10,15,12,15,229,9,15,1,15,1,15,1,16,1,16,1,16,1,16,1,
		16,1,16,1,16,1,16,1,17,1,17,1,17,1,17,1,17,1,18,1,18,3,18,248,8,18,1,18,
		1,18,1,19,1,19,1,19,1,19,1,19,3,19,257,8,19,1,20,1,20,1,20,1,20,1,20,1,
		20,1,21,1,21,1,21,1,21,1,22,1,22,1,22,1,22,5,22,273,8,22,10,22,12,22,276,
		9,22,1,22,1,22,1,23,1,23,1,23,1,23,1,23,1,24,1,24,5,24,287,8,24,10,24,
		12,24,290,9,24,1,24,1,24,1,25,1,25,1,26,1,26,1,26,1,26,5,26,300,8,26,10,
		26,12,26,303,9,26,1,27,1,27,1,27,1,27,1,27,1,27,1,27,3,27,312,8,27,1,28,
		1,28,1,28,1,28,1,28,5,28,319,8,28,10,28,12,28,322,9,28,3,28,324,8,28,1,
		28,1,28,1,29,1,29,1,29,4,29,331,8,29,11,29,12,29,332,1,30,1,30,1,30,0,
		0,31,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,
		48,50,52,54,56,58,60,0,1,2,0,18,21,23,31,351,0,67,1,0,0,0,2,70,1,0,0,0,
		4,78,1,0,0,0,6,100,1,0,0,0,8,102,1,0,0,0,10,116,1,0,0,0,12,127,1,0,0,0,
		14,135,1,0,0,0,16,146,1,0,0,0,18,162,1,0,0,0,20,170,1,0,0,0,22,184,1,0,
		0,0,24,204,1,0,0,0,26,212,1,0,0,0,28,218,1,0,0,0,30,220,1,0,0,0,32,232,
		1,0,0,0,34,240,1,0,0,0,36,245,1,0,0,0,38,251,1,0,0,0,40,258,1,0,0,0,42,
		264,1,0,0,0,44,268,1,0,0,0,46,279,1,0,0,0,48,284,1,0,0,0,50,293,1,0,0,
		0,52,295,1,0,0,0,54,311,1,0,0,0,56,313,1,0,0,0,58,327,1,0,0,0,60,334,1,
		0,0,0,62,66,3,4,2,0,63,66,3,2,1,0,64,66,3,6,3,0,65,62,1,0,0,0,65,63,1,
		0,0,0,65,64,1,0,0,0,66,69,1,0,0,0,67,65,1,0,0,0,67,68,1,0,0,0,68,1,1,0,
		0,0,69,67,1,0,0,0,70,71,5,1,0,0,71,75,5,44,0,0,72,74,3,6,3,0,73,72,1,0,
		0,0,74,77,1,0,0,0,75,73,1,0,0,0,75,76,1,0,0,0,76,3,1,0,0,0,77,75,1,0,0,
		0,78,79,5,2,0,0,79,84,5,44,0,0,80,81,5,41,0,0,81,83,5,44,0,0,82,80,1,0,
		0,0,83,86,1,0,0,0,84,82,1,0,0,0,84,85,1,0,0,0,85,5,1,0,0,0,86,84,1,0,0,
		0,87,101,3,8,4,0,88,101,3,14,7,0,89,101,3,16,8,0,90,101,3,22,11,0,91,101,
		3,20,10,0,92,101,3,32,16,0,93,101,3,34,17,0,94,101,3,36,18,0,95,101,3,
		38,19,0,96,101,3,40,20,0,97,101,3,42,21,0,98,101,3,44,22,0,99,101,3,50,
		25,0,100,87,1,0,0,0,100,88,1,0,0,0,100,89,1,0,0,0,100,90,1,0,0,0,100,91,
		1,0,0,0,100,92,1,0,0,0,100,93,1,0,0,0,100,94,1,0,0,0,100,95,1,0,0,0,100,
		96,1,0,0,0,100,97,1,0,0,0,100,98,1,0,0,0,100,99,1,0,0,0,101,7,1,0,0,0,
		102,103,5,15,0,0,103,105,5,44,0,0,104,106,3,10,5,0,105,104,1,0,0,0,105,
		106,1,0,0,0,106,107,1,0,0,0,107,111,5,34,0,0,108,110,3,12,6,0,109,108,
		1,0,0,0,110,113,1,0,0,0,111,109,1,0,0,0,111,112,1,0,0,0,112,114,1,0,0,
		0,113,111,1,0,0,0,114,115,5,35,0,0,115,9,1,0,0,0,116,117,5,25,0,0,117,
		122,3,28,14,0,118,119,5,40,0,0,119,121,3,28,14,0,120,118,1,0,0,0,121,124,
		1,0,0,0,122,120,1,0,0,0,122,123,1,0,0,0,123,125,1,0,0,0,124,122,1,0,0,
		0,125,126,5,26,0,0,126,11,1,0,0,0,127,128,5,14,0,0,128,133,5,44,0,0,129,
		130,5,32,0,0,130,131,3,28,14,0,131,132,5,33,0,0,132,134,1,0,0,0,133,129,
		1,0,0,0,133,134,1,0,0,0,134,13,1,0,0,0,135,136,5,8,0,0,136,137,5,44,0,
		0,137,141,5,34,0,0,138,140,3,22,11,0,139,138,1,0,0,0,140,143,1,0,0,0,141,
		139,1,0,0,0,141,142,1,0,0,0,142,144,1,0,0,0,143,141,1,0,0,0,144,145,5,
		35,0,0,145,15,1,0,0,0,146,147,5,4,0,0,147,150,5,44,0,0,148,149,5,39,0,
		0,149,151,5,44,0,0,150,148,1,0,0,0,150,151,1,0,0,0,151,152,1,0,0,0,152,
		157,5,34,0,0,153,156,3,18,9,0,154,156,3,22,11,0,155,153,1,0,0,0,155,154,
		1,0,0,0,156,159,1,0,0,0,157,155,1,0,0,0,157,158,1,0,0,0,158,160,1,0,0,
		0,159,157,1,0,0,0,160,161,5,35,0,0,161,17,1,0,0,0,162,163,5,5,0,0,163,
		164,5,44,0,0,164,165,5,39,0,0,165,166,3,28,14,0,166,167,5,22,0,0,167,168,
		3,52,26,0,168,169,5,38,0,0,169,19,1,0,0,0,170,171,5,7,0,0,171,172,5,44,
		0,0,172,173,5,25,0,0,173,174,5,44,0,0,174,175,5,26,0,0,175,179,5,34,0,
		0,176,178,3,6,3,0,177,176,1,0,0,0,178,181,1,0,0,0,179,177,1,0,0,0,179,
		180,1,0,0,0,180,182,1,0,0,0,181,179,1,0,0,0,182,183,5,35,0,0,183,21,1,
		0,0,0,184,185,5,3,0,0,185,186,5,44,0,0,186,188,5,32,0,0,187,189,3,24,12,
		0,188,187,1,0,0,0,188,189,1,0,0,0,189,190,1,0,0,0,190,193,5,33,0,0,191,
		192,5,42,0,0,192,194,3,28,14,0,193,191,1,0,0,0,193,194,1,0,0,0,194,195,
		1,0,0,0,195,199,5,34,0,0,196,198,3,6,3,0,197,196,1,0,0,0,198,201,1,0,0,
		0,199,197,1,0,0,0,199,200,1,0,0,0,200,202,1,0,0,0,201,199,1,0,0,0,202,
		203,5,35,0,0,203,23,1,0,0,0,204,209,3,26,13,0,205,206,5,40,0,0,206,208,
		3,26,13,0,207,205,1,0,0,0,208,211,1,0,0,0,209,207,1,0,0,0,209,210,1,0,
		0,0,210,25,1,0,0,0,211,209,1,0,0,0,212,213,5,44,0,0,213,214,5,39,0,0,214,
		215,3,28,14,0,215,27,1,0,0,0,216,219,5,44,0,0,217,219,3,30,15,0,218,216,
		1,0,0,0,218,217,1,0,0,0,219,29,1,0,0,0,220,221,5,44,0,0,221,222,5,25,0,
		0,222,227,3,28,14,0,223,224,5,40,0,0,224,226,3,28,14,0,225,223,1,0,0,0,
		226,229,1,0,0,0,227,225,1,0,0,0,227,228,1,0,0,0,228,230,1,0,0,0,229,227,
		1,0,0,0,230,231,5,26,0,0,231,31,1,0,0,0,232,233,5,6,0,0,233,234,5,44,0,
		0,234,235,5,39,0,0,235,236,3,28,14,0,236,237,5,22,0,0,237,238,3,52,26,
		0,238,239,5,38,0,0,239,33,1,0,0,0,240,241,5,44,0,0,241,242,5,22,0,0,242,
		243,3,52,26,0,243,244,5,38,0,0,244,35,1,0,0,0,245,247,5,16,0,0,246,248,
		3,52,26,0,247,246,1,0,0,0,247,248,1,0,0,0,248,249,1,0,0,0,249,250,5,38,
		0,0,250,37,1,0,0,0,251,252,5,9,0,0,252,253,3,52,26,0,253,256,3,48,24,0,
		254,255,5,10,0,0,255,257,3,48,24,0,256,254,1,0,0,0,256,257,1,0,0,0,257,
		39,1,0,0,0,258,259,5,11,0,0,259,260,5,44,0,0,260,261,5,43,0,0,261,262,
		3,52,26,0,262,263,3,48,24,0,263,41,1,0,0,0,264,265,5,12,0,0,265,266,3,
		52,26,0,266,267,3,48,24,0,267,43,1,0,0,0,268,269,5,13,0,0,269,270,3,52,
		26,0,270,274,5,34,0,0,271,273,3,46,23,0,272,271,1,0,0,0,273,276,1,0,0,
		0,274,272,1,0,0,0,274,275,1,0,0,0,275,277,1,0,0,0,276,274,1,0,0,0,277,
		278,5,35,0,0,278,45,1,0,0,0,279,280,5,14,0,0,280,281,3,52,26,0,281,282,
		5,39,0,0,282,283,3,48,24,0,283,47,1,0,0,0,284,288,5,34,0,0,285,287,3,6,
		3,0,286,285,1,0,0,0,287,290,1,0,0,0,288,286,1,0,0,0,288,289,1,0,0,0,289,
		291,1,0,0,0,290,288,1,0,0,0,291,292,5,35,0,0,292,49,1,0,0,0,293,294,3,
		52,26,0,294,51,1,0,0,0,295,301,3,54,27,0,296,297,3,60,30,0,297,298,3,54,
		27,0,298,300,1,0,0,0,299,296,1,0,0,0,300,303,1,0,0,0,301,299,1,0,0,0,301,
		302,1,0,0,0,302,53,1,0,0,0,303,301,1,0,0,0,304,312,5,44,0,0,305,312,5,
		45,0,0,306,312,5,46,0,0,307,312,5,47,0,0,308,312,5,48,0,0,309,312,3,56,
		28,0,310,312,3,58,29,0,311,304,1,0,0,0,311,305,1,0,0,0,311,306,1,0,0,0,
		311,307,1,0,0,0,311,308,1,0,0,0,311,309,1,0,0,0,311,310,1,0,0,0,312,55,
		1,0,0,0,313,314,5,44,0,0,314,323,5,32,0,0,315,320,3,52,26,0,316,317,5,
		40,0,0,317,319,3,52,26,0,318,316,1,0,0,0,319,322,1,0,0,0,320,318,1,0,0,
		0,320,321,1,0,0,0,321,324,1,0,0,0,322,320,1,0,0,0,323,315,1,0,0,0,323,
		324,1,0,0,0,324,325,1,0,0,0,325,326,5,33,0,0,326,57,1,0,0,0,327,330,5,
		44,0,0,328,329,5,41,0,0,329,331,5,44,0,0,330,328,1,0,0,0,331,332,1,0,0,
		0,332,330,1,0,0,0,332,333,1,0,0,0,333,59,1,0,0,0,334,335,7,0,0,0,335,61,
		1,0,0,0,29,65,67,75,84,100,105,111,122,133,141,150,155,157,179,188,193,
		199,209,218,227,247,256,274,288,301,311,320,323,332
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
